# Without multi-stage implementation
FROM node:24-alpine3.23

WORKDIR /home/app

COPY package*.json .
COPY tsconfig.json .

RUN npm install

COPY src/ src/

# makes the dist folder 
RUN npm run build

# will run from the dist folder as seen in package.json
CMD ["npm","start"]
